### ISSUE TITLE
Provide binaries via AppVeyor

### ISSUE THREAD

**Issue by beatcracker** [nikvoronin/ClooToOpenGL#1]
I'm too lazy to build this myself. Could you use something like  [AppVeyor](https://www.appveyor.com) to provide binaries?

**Comment by nikvoronin** [comment]
Under the [release section](https://github.com/nikvoronin/ClooToOpenGL/releases/latest) you can find compiled binaries. Direct link: https://github.com/nikvoronin/ClooToOpenGL/releases/download/v1.0/ClooToOpenGL-1.0.zip
